apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
spec:
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce
        env:
          - name: GITLAB_OMNIBUS_CONFIG
            value: " external_url 'http://gitlab.itlabs.us:31801/';gitlab_rails['registry_enabled'] = true;gitlab_rails['initial_root_password'] = 'adminadmin'"
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
          - mountPath: /var/opt/gitlab
            name: data
      volumes:
        - name: data
          emptyDir: {}